### ISSUE TITLE
log-pilot-fluentd多行日志

### ISSUE THREAD

**Issue by loveyang2012** [WilliamGuozi/log-pilot-filebeat#1]
大神好，log-pilot-fluentd多行日志，模板配置样例也来一份呗

**Comment by WilliamGuozi** [comment]
@loveyang2012

![image](https://user-images.githubusercontent.com/30142292/83478171-c17f1600-a4c7-11ea-8182-e602d7c5ef33.png)
抱歉, 消息回的有点晚了， fluentd没怎么研究过， 不过推荐使用filebeat， 它的性能远优于fluentd
