### ISSUE TITLE
您好 我和你一样使用log-pilot  filebeat 

### ISSUE THREAD

**Issue by denycall** [WilliamGuozi/log-pilot-filebeat#2]
index: "${ELASTICSEARCH_INDEX:-filebeat}-%{+YYYY.MM}"
将模板参数修改为这样，filebeat还是创建的是 年月日的索引，有遇到过吗

**Comment by WilliamGuozi** [comment]
> ```
> index: "${ELASTICSEARCH_INDEX:-filebeat}-%{+YYYY.MM}"
> ```
> 
> 将模板参数修改为这样，filebeat还是创建的是 年月日的索引，有遇到过吗

需要添加这个文件24-26行，重新制作镜像，默认会使用 filebeat 生成的索引，需要将索引drop掉， 让output重新生成
https://github.com/WilliamGuozi/log-pilot-filebeat/blob/4c969a68f601aa4837766b33c0bea6094e42f665/filebeat.tpl
```
  processors:
   - drop_fields:
       fields: ["index"]
```

**Comment by WilliamGuozi** [comment]
> ```
> index: "${ELASTICSEARCH_INDEX:-filebeat}-%{+YYYY.MM}"
> ```
> 
> 将模板参数修改为这样，filebeat还是创建的是 年月日的索引，有遇到过吗

需要在模版配置文件 filebeat.tpl 中将 index drop掉（24-26行），让output重新生成
https://github.com/WilliamGuozi/log-pilot-filebeat/blob/4c969a68f601aa4837766b33c0bea6094e42f665/filebeat.tpl
